<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert([
            [
                'name' => 'T-shirt_tmp_name',
                'information' => 'T-shirt_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 1,
                'shop_id' => 1,
                'secondary_category_id' => 1,
                'image1' => 4,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'T-shirt_tmp_name',
                'information' => 'T-shirt_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 2,
                'shop_id' => 1,
                'secondary_category_id' => 1,
                'image1' => 5,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'T-shirt_tmp_name',
                'information' => 'T-shirt_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 3,
                'shop_id' => 1,
                'secondary_category_id' => 1,
                'image1' => 6,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'T-shirt_tmp_name',
                'information' => 'T-shirt_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 4,
                'shop_id' => 1,
                'secondary_category_id' => 1,
                'image1' => 7,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'T-shirt_tmp_name',
                'information' => 'T-shirt_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 5,
                'shop_id' => 1,
                'secondary_category_id' => 1,
                'image1' => 8,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'T-shirt_tmp_name',
                'information' => 'T-shirt_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 6,
                'shop_id' => 1,
                'secondary_category_id' => 1,
                'image1' => 9,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'T-shirt_tmp_name',
                'information' => 'T-shirt_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 7,
                'shop_id' => 1,
                'secondary_category_id' => 1,
                'image1' => 10,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'T-shirt_tmp_name',
                'information' => 'T-shirt_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 8,
                'shop_id' => 2,
                'secondary_category_id' => 1,
                'image1' => 11,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'T-shirt_tmp_name',
                'information' => 'T-shirt_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 9,
                'shop_id' => 2,
                'secondary_category_id' => 1,
                'image1' => 12,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'T-shirt_tmp_name',
                'information' => 'T-shirt_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 10,
                'shop_id' => 2,
                'secondary_category_id' => 1,
                'image1' => 13,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'T-shirt_tmp_name',
                'information' => 'T-shirt_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 11,
                'shop_id' => 2,
                'secondary_category_id' => 1,
                'image1' => 14,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'T-shirt_tmp_name',
                'information' => 'T-shirt_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 12,
                'shop_id' => 2,
                'secondary_category_id' => 1,
                'image1' => 15,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'T-shirt_tmp_name',
                'information' => 'T-shirt_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 13,
                'shop_id' => 2,
                'secondary_category_id' => 1,
                'image1' => 16,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'T-shirt_tmp_name',
                'information' => 'T-shirt_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 14,
                'shop_id' => 2,
                'secondary_category_id' => 1,
                'image1' => 17,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'T-shirt_tmp_name',
                'information' => 'T-shirt_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 15,
                'shop_id' => 3,
                'secondary_category_id' => 1,
                'image1' => 18,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'T-shirt_tmp_name',
                'information' => 'T-shirt_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 16,
                'shop_id' => 3,
                'secondary_category_id' => 1,
                'image1' => 19,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'T-shirt_tmp_name',
                'information' => 'T-shirt_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 17,
                'shop_id' => 3,
                'secondary_category_id' => 1,
                'image1' => 20,
                'image2' => 21,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'T-shirt_tmp_name',
                'information' => 'T-shirt_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 18,
                'shop_id' => 3,
                'secondary_category_id' => 1,
                'image1' => 22,
                'image2' => 23,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Hoodie_tmp_name',
                'information' => 'Hoodie_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 19,
                'shop_id' => 1,
                'secondary_category_id' => 2,
                'image1' => 24,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Hoodie_tmp_name',
                'information' => 'Hoodie_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 20,
                'shop_id' => 1,
                'secondary_category_id' => 2,
                'image1' => 25,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Hoodie_tmp_name',
                'information' => 'Hoodie_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 21,
                'shop_id' => 1,
                'secondary_category_id' => 2,
                'image1' => 26,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Hoodie_tmp_name',
                'information' => 'Hoodie_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 22,
                'shop_id' => 1,
                'secondary_category_id' => 2,
                'image1' => 27,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Hoodie_tmp_name',
                'information' => 'Hoodie_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 23,
                'shop_id' => 1,
                'secondary_category_id' => 2,
                'image1' => 28,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Hoodie_tmp_name',
                'information' => 'Hoodie_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 24,
                'shop_id' => 1,
                'secondary_category_id' => 2,
                'image1' => 29,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Hoodie_tmp_name',
                'information' => 'Hoodie_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 25,
                'shop_id' => 1,
                'secondary_category_id' => 2,
                'image1' => 30,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Hoodie_tmp_name',
                'information' => 'Hoodie_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 26,
                'shop_id' => 1,
                'secondary_category_id' => 2,
                'image1' => 31,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Hoodie_tmp_name',
                'information' => 'Hoodie_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 27,
                'shop_id' => 1,
                'secondary_category_id' => 2,
                'image1' => 32,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Hoodie_tmp_name',
                'information' => 'Hoodie_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 28,
                'shop_id' => 1,
                'secondary_category_id' => 2,
                'image1' => 33,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Hoodie_tmp_name',
                'information' => 'Hoodie_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 29,
                'shop_id' => 2,
                'secondary_category_id' => 2,
                'image1' => 34,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Hoodie_tmp_name',
                'information' => 'Hoodie_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 30,
                'shop_id' => 2,
                'secondary_category_id' => 2,
                'image1' => 35,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Hoodie_tmp_name',
                'information' => 'Hoodie_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 31,
                'shop_id' => 2,
                'secondary_category_id' => 2,
                'image1' => 36,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Hoodie_tmp_name',
                'information' => 'Hoodie_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 32,
                'shop_id' => 2,
                'secondary_category_id' => 2,
                'image1' => 37,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Hoodie_tmp_name',
                'information' => 'Hoodie_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 33,
                'shop_id' => 2,
                'secondary_category_id' => 2,
                'image1' => 38,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Hoodie_tmp_name',
                'information' => 'Hoodie_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 34,
                'shop_id' => 2,
                'secondary_category_id' => 2,
                'image1' => 39,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Hoodie_tmp_name',
                'information' => 'Hoodie_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 35,
                'shop_id' => 2,
                'secondary_category_id' => 2,
                'image1' => 40,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Hoodie_tmp_name',
                'information' => 'Hoodie_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 36,
                'shop_id' => 2,
                'secondary_category_id' => 2,
                'image1' => 41,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Hoodie_tmp_name',
                'information' => 'Hoodie_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 37,
                'shop_id' => 2,
                'secondary_category_id' => 2,
                'image1' => 42,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Hoodie_tmp_name',
                'information' => 'Hoodie_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 38,
                'shop_id' => 2,
                'secondary_category_id' => 2,
                'image1' => 43,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Hoodie_tmp_name',
                'information' => 'Hoodie_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 39,
                'shop_id' => 3,
                'secondary_category_id' => 2,
                'image1' => 44,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Hoodie_tmp_name',
                'information' => 'Hoodie_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 40,
                'shop_id' => 3,
                'secondary_category_id' => 2,
                'image1' => 45,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Hoodie_tmp_name',
                'information' => 'Hoodie_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 41,
                'shop_id' => 3,
                'secondary_category_id' => 2,
                'image1' => 46,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Hoodie_tmp_name',
                'information' => 'Hoodie_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 42,
                'shop_id' => 3,
                'secondary_category_id' => 2,
                'image1' => 47,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Hoodie_tmp_name',
                'information' => 'Hoodie_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 43,
                'shop_id' => 3,
                'secondary_category_id' => 2,
                'image1' => 48,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Hoodie_tmp_name',
                'information' => 'Hoodie_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 44,
                'shop_id' => 3,
                'secondary_category_id' => 2,
                'image1' => 49,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Hoodie_tmp_name',
                'information' => 'Hoodie_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 45,
                'shop_id' => 3,
                'secondary_category_id' => 2,
                'image1' => 50,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Hoodie_tmp_name',
                'information' => 'Hoodie_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 46,
                'shop_id' => 3,
                'secondary_category_id' => 2,
                'image1' => 51,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Hoodie_tmp_name',
                'information' => 'Hoodie_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 47,
                'shop_id' => 3,
                'secondary_category_id' => 2,
                'image1' => 52,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Hoodie_tmp_name',
                'information' => 'Hoodie_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 48,
                'shop_id' => 3,
                'secondary_category_id' => 2,
                'image1' => 53,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Sweatshirt_tmp_name',
                'information' => 'Sweatshirt_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 49,
                'shop_id' => 1,
                'secondary_category_id' => 3,
                'image1' => 54,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Sweatshirt_tmp_name',
                'information' => 'Sweatshirt_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 50,
                'shop_id' => 1,
                'secondary_category_id' => 3,
                'image1' => 55,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Sweatshirt_tmp_name',
                'information' => 'Sweatshirt_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 51,
                'shop_id' => 1,
                'secondary_category_id' => 3,
                'image1' => 56,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Sweatshirt_tmp_name',
                'information' => 'Sweatshirt_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 52,
                'shop_id' => 2,
                'secondary_category_id' => 3,
                'image1' => 57,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Sweatshirt_tmp_name',
                'information' => 'Sweatshirt_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 53,
                'shop_id' => 2,
                'secondary_category_id' => 3,
                'image1' => 58,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Sweatshirt_tmp_name',
                'information' => 'Sweatshirt_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 54,
                'shop_id' => 3,
                'secondary_category_id' => 3,
                'image1' => 59,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Sweatshirt_tmp_name',
                'information' => 'Sweatshirt_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 55,
                'shop_id' => 3,
                'secondary_category_id' => 3,
                'image1' => 60,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Jacket_tmp_name',
                'information' => 'Jacket_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 56,
                'shop_id' => 1,
                'secondary_category_id' => 4,
                'image1' => 61,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Jacket_tmp_name',
                'information' => 'Jacket_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 57,
                'shop_id' => 1,
                'secondary_category_id' => 4,
                'image1' => 62,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Jacket_tmp_name',
                'information' => 'Jacket_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 58,
                'shop_id' => 1,
                'secondary_category_id' => 4,
                'image1' => 63,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Jacket_tmp_name',
                'information' => 'Jacket_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 59,
                'shop_id' => 1,
                'secondary_category_id' => 4,
                'image1' => 64,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Jacket_tmp_name',
                'information' => 'Jacket_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 60,
                'shop_id' => 1,
                'secondary_category_id' => 4,
                'image1' => 65,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Jacket_tmp_name',
                'information' => 'Jacket_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 61,
                'shop_id' => 2,
                'secondary_category_id' => 4,
                'image1' => 66,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Jacket_tmp_name',
                'information' => 'Jacket_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 62,
                'shop_id' => 2,
                'secondary_category_id' => 4,
                'image1' => 67,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Jacket_tmp_name',
                'information' => 'Jacket_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 63,
                'shop_id' => 2,
                'secondary_category_id' => 4,
                'image1' => 68,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Jacket_tmp_name',
                'information' => 'Jacket_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 64,
                'shop_id' => 2,
                'secondary_category_id' => 4,
                'image1' => 69,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Jacket_tmp_name',
                'information' => 'Jacket_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 65,
                'shop_id' => 2,
                'secondary_category_id' => 4,
                'image1' => 70,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Jacket_tmp_name',
                'information' => 'Jacket_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 66,
                'shop_id' => 3,
                'secondary_category_id' => 4,
                'image1' => 71,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Jacket_tmp_name',
                'information' => 'Jacket_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 67,
                'shop_id' => 3,
                'secondary_category_id' => 4,
                'image1' => 72,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Jacket_tmp_name',
                'information' => 'Jacket_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 68,
                'shop_id' => 3,
                'secondary_category_id' => 4,
                'image1' => 73,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Jacket_tmp_name',
                'information' => 'Jacket_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 69,
                'shop_id' => 3,
                'secondary_category_id' => 4,
                'image1' => 74,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Cap_tmp_name',
                'information' => 'Cap_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 70,
                'shop_id' => 1,
                'secondary_category_id' => 5,
                'image1' => 75,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Cap_tmp_name',
                'information' => 'Cap_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 71,
                'shop_id' => 1,
                'secondary_category_id' => 5,
                'image1' => 76,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Cap_tmp_name',
                'information' => 'Cap_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 72,
                'shop_id' => 1,
                'secondary_category_id' => 5,
                'image1' => 77,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Cap_tmp_name',
                'information' => 'Cap_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 73,
                'shop_id' => 2,
                'secondary_category_id' => 5,
                'image1' => 78,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Cap_tmp_name',
                'information' => 'Cap_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 74,
                'shop_id' => 2,
                'secondary_category_id' => 5,
                'image1' => 79,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Cap_tmp_name',
                'information' => 'Cap_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 75,
                'shop_id' => 2,
                'secondary_category_id' => 5,
                'image1' => 80,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Cap_tmp_name',
                'information' => 'Cap_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 76,
                'shop_id' => 3,
                'secondary_category_id' => 5,
                'image1' => 81,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Cap_tmp_name',
                'information' => 'Cap_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 77,
                'shop_id' => 3,
                'secondary_category_id' => 5,
                'image1' => 82,
                'image2' => 83,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Scarf_Towel_tmp_name',
                'information' => 'Scarf_Towel_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 78,
                'shop_id' => 1,
                'secondary_category_id' => 6,
                'image1' => 84,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Scarf_Towel_tmp_name',
                'information' => 'Scarf_Towel_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 79,
                'shop_id' => 1,
                'secondary_category_id' => 6,
                'image1' => 85,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Scarf_Towel_tmp_name',
                'information' => 'Scarf_Towel_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 80,
                'shop_id' => 1,
                'secondary_category_id' => 6,
                'image1' => 86,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Scarf_Towel_tmp_name',
                'information' => 'Scarf_Towel_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 81,
                'shop_id' => 1,
                'secondary_category_id' => 6,
                'image1' => 87,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Scarf_Towel_tmp_name',
                'information' => 'Scarf_Towel_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 82,
                'shop_id' => 2,
                'secondary_category_id' => 6,
                'image1' => 88,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Scarf_Towel_tmp_name',
                'information' => 'Scarf_Towel_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 83,
                'shop_id' => 2,
                'secondary_category_id' => 6,
                'image1' => 89,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Scarf_Towel_tmp_name',
                'information' => 'Scarf_Towel_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 84,
                'shop_id' => 2,
                'secondary_category_id' => 6,
                'image1' => 90,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Scarf_Towel_tmp_name',
                'information' => 'Scarf_Towel_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 85,
                'shop_id' => 3,
                'secondary_category_id' => 6,
                'image1' => 91,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Scarf_Towel_tmp_name',
                'information' => 'Scarf_Towel_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 86,
                'shop_id' => 3,
                'secondary_category_id' => 6,
                'image1' => 92,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Scarf_Towel_tmp_name',
                'information' => 'Scarf_Towel_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 87,
                'shop_id' => 3,
                'secondary_category_id' => 6,
                'image1' => 93,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Face_Towel_tmp_name',
                'information' => 'Face_Towel_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 88,
                'shop_id' => 1,
                'secondary_category_id' => 7,
                'image1' => 94,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Face_Towel_tmp_name',
                'information' => 'Face_Towel_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 89,
                'shop_id' => 1,
                'secondary_category_id' => 7,
                'image1' => 95,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Face_Towel_tmp_name',
                'information' => 'Face_Towel_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 90,
                'shop_id' => 2,
                'secondary_category_id' => 7,
                'image1' => 96,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Face_Towel_tmp_name',
                'information' => 'Face_Towel_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 91,
                'shop_id' => 2,
                'secondary_category_id' => 7,
                'image1' => 97,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Face_Towel_tmp_name',
                'information' => 'Face_Towel_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 92,
                'shop_id' => 3,
                'secondary_category_id' => 7,
                'image1' => 98,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Face_Towel_tmp_name',
                'information' => 'Face_Towel_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 93,
                'shop_id' => 3,
                'secondary_category_id' => 7,
                'image1' => 99,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Mini_Towel_tmp_name',
                'information' => 'Mini_Towel_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 94,
                'shop_id' => 1,
                'secondary_category_id' => 8,
                'image1' => 100,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Mini_Towel_tmp_name',
                'information' => 'Mini_Towel_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 95,
                'shop_id' => 1,
                'secondary_category_id' => 8,
                'image1' => 101,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Mini_Towel_tmp_name',
                'information' => 'Mini_Towel_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 96,
                'shop_id' => 2,
                'secondary_category_id' => 8,
                'image1' => 102,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Mini_Towel_tmp_name',
                'information' => 'Mini_Towel_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 97,
                'shop_id' => 3,
                'secondary_category_id' => 8,
                'image1' => 103,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Tote_Bag_tmp_name',
                'information' => 'Tote_Bag_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 98,
                'shop_id' => 1,
                'secondary_category_id' => 9,
                'image1' => 104,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Tote_Bag_tmp_name',
                'information' => 'Tote_Bag_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 99,
                'shop_id' => 1,
                'secondary_category_id' => 9,
                'image1' => 105,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Tote_Bag_tmp_name',
                'information' => 'Tote_Bag_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 100,
                'shop_id' => 1,
                'secondary_category_id' => 9,
                'image1' => 106,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Tote_Bag_tmp_name',
                'information' => 'Tote_Bag_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 101,
                'shop_id' => 2,
                'secondary_category_id' => 9,
                'image1' => 107,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Tote_Bag_tmp_name',
                'information' => 'Tote_Bag_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 102,
                'shop_id' => 2,
                'secondary_category_id' => 9,
                'image1' => 108,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Tote_Bag_tmp_name',
                'information' => 'Tote_Bag_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 103,
                'shop_id' => 2,
                'secondary_category_id' => 9,
                'image1' => 109,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Tote_Bag_tmp_name',
                'information' => 'Tote_Bag_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 104,
                'shop_id' => 3,
                'secondary_category_id' => 9,
                'image1' => 110,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Tote_Bag_tmp_name',
                'information' => 'Tote_Bag_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 105,
                'shop_id' => 3,
                'secondary_category_id' => 9,
                'image1' => 111,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Shoulder_Bag_tmp_name',
                'information' => 'Shoulder_Bag_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 106,
                'shop_id' => 1,
                'secondary_category_id' => 10,
                'image1' => 112,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Shoulder_Bag_tmp_name',
                'information' => 'Shoulder_Bag_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 107,
                'shop_id' => 1,
                'secondary_category_id' => 10,
                'image1' => 113,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Shoulder_Bag_tmp_name',
                'information' => 'Shoulder_Bag_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 108,
                'shop_id' => 2,
                'secondary_category_id' => 10,
                'image1' => 114,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Shoulder_Bag_tmp_name',
                'information' => 'Shoulder_Bag_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 109,
                'shop_id' => 3,
                'secondary_category_id' => 10,
                'image1' => 115,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Rubber_Band_tmp_name',
                'information' => 'Rubber_Band_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 110,
                'shop_id' => 1,
                'secondary_category_id' => 11,
                'image1' => 116,
                'image2' => 117,
                'image3' => 118,
                'image4' => null,
            ],
            [
                'name' => 'Keychain_tmp_name',
                'information' => 'Keychain_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 111,
                'shop_id' => 1,
                'secondary_category_id' => 12,
                'image1' => 119,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Keychain_tmp_name',
                'information' => 'Keychain_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 112,
                'shop_id' => 1,
                'secondary_category_id' => 12,
                'image1' => 120,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Keychain_tmp_name',
                'information' => 'Keychain_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 113,
                'shop_id' => 1,
                'secondary_category_id' => 12,
                'image1' => 121,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Keychain_tmp_name',
                'information' => 'Keychain_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 114,
                'shop_id' => 1,
                'secondary_category_id' => 12,
                'image1' => 122,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Keychain_tmp_name',
                'information' => 'Keychain_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 115,
                'shop_id' => 2,
                'secondary_category_id' => 12,
                'image1' => 123,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Keychain_tmp_name',
                'information' => 'Keychain_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 116,
                'shop_id' => 2,
                'secondary_category_id' => 12,
                'image1' => 124,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Keychain_tmp_name',
                'information' => 'Keychain_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 117,
                'shop_id' => 2,
                'secondary_category_id' => 12,
                'image1' => 125,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Keychain_tmp_name',
                'information' => 'Keychain_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 118,
                'shop_id' => 2,
                'secondary_category_id' => 12,
                'image1' => 126,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Keychain_tmp_name',
                'information' => 'Keychain_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 119,
                'shop_id' => 3,
                'secondary_category_id' => 12,
                'image1' => 127,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Keychain_tmp_name',
                'information' => 'Keychain_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 120,
                'shop_id' => 3,
                'secondary_category_id' => 12,
                'image1' => 128,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Keychain_tmp_name',
                'information' => 'Keychain_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 121,
                'shop_id' => 3,
                'secondary_category_id' => 12,
                'image1' => 129,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Badge_tmp_name',
                'information' => 'Badge_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 122,
                'shop_id' => 1,
                'secondary_category_id' => 13,
                'image1' => 130,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Badge_tmp_name',
                'information' => 'Badge_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 123,
                'shop_id' => 1,
                'secondary_category_id' => 13,
                'image1' => 131,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Badge_tmp_name',
                'information' => 'Badge_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 124,
                'shop_id' => 1,
                'secondary_category_id' => 13,
                'image1' => 132,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Badge_tmp_name',
                'information' => 'Badge_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 125,
                'shop_id' => 2,
                'secondary_category_id' => 13,
                'image1' => 133,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Badge_tmp_name',
                'information' => 'Badge_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 126,
                'shop_id' => 2,
                'secondary_category_id' => 13,
                'image1' => 134,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Badge_tmp_name',
                'information' => 'Badge_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 127,
                'shop_id' => 3,
                'secondary_category_id' => 13,
                'image1' => 135,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Badge_tmp_name',
                'information' => 'Badge_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 128,
                'shop_id' => 3,
                'secondary_category_id' => 13,
                'image1' => 136,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Sticker_tmp_name',
                'information' => 'Sticker_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 129,
                'shop_id' => 1,
                'secondary_category_id' => 14,
                'image1' => 137,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Sticker_tmp_name',
                'information' => 'Sticker_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 130,
                'shop_id' => 1,
                'secondary_category_id' => 14,
                'image1' => 138,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Sticker_tmp_name',
                'information' => 'Sticker_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 131,
                'shop_id' => 2,
                'secondary_category_id' => 14,
                'image1' => 139,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Sticker_tmp_name',
                'information' => 'Sticker_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 132,
                'shop_id' => 3,
                'secondary_category_id' => 14,
                'image1' => 140,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Calendar_tmp_name',
                'information' => 'Calendar_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 133,
                'shop_id' => 1,
                'secondary_category_id' => 15,
                'image1' => 141,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Calendar_tmp_name',
                'information' => 'Calendar_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 134,
                'shop_id' => 2,
                'secondary_category_id' => 15,
                'image1' => 142,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Calendar_tmp_name',
                'information' => 'Calendar_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 135,
                'shop_id' => 3,
                'secondary_category_id' => 15,
                'image1' => 143,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'iPhone_tmp_name',
                'information' => 'iPhone_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 136,
                'shop_id' => 1,
                'secondary_category_id' => 16,
                'image1' => 144,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'iPhone_tmp_name',
                'information' => 'iPhone_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 137,
                'shop_id' => 2,
                'secondary_category_id' => 16,
                'image1' => 145,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'iPhone_tmp_name',
                'information' => 'iPhone_tmp_information',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 138,
                'shop_id' => 3,
                'secondary_category_id' => 16,
                'image1' => 146,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
        ]);
    }

    private function randomNumber()
    {
        return rand(1000, 8000);
    }
}
