<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert([
            [
                'name' => 'Electric Vibes T-shirt',
                'information' => 'エレクトロニックミュージックのビートを象徴する鮮やかな波形デザイン。ポリエステル素材で速乾性に優れています。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 1,
                'shop_id' => 1,
                'secondary_category_id' => 1,
                'image1' => 4,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Rock n’ Roll Legends T-shirt',
                'information' => '伝説のロックスターたちのシルエットが描かれたクールなTシャツ。コットン100%で肌触り抜群。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 2,
                'shop_id' => 1,
                'secondary_category_id' => 1,
                'image1' => 5,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Jazz Groove T-shirt',
                'information' => 'ジャズのサックスとピアノのモチーフが胸元にデザインされたおしゃれなTシャツ。リラックスフィットで着心地が良い。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 3,
                'shop_id' => 1,
                'secondary_category_id' => 1,
                'image1' => 6,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Summer Beats T-shirt',
                'information' => '夏の音楽フェスをイメージしたカラフルなデザイン。軽量素材で快適な着心地を提供。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 4,
                'shop_id' => 1,
                'secondary_category_id' => 1,
                'image1' => 7,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Urban Rhythm T-shirt',
                'information' => '都会的なリズムをテーマにしたモノクロームデザイン。スタイリッシュでどんなシーンにも合わせやすい。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 5,
                'shop_id' => 1,
                'secondary_category_id' => 1,
                'image1' => 8,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Vinyl Lover’s T-shirt',
                'information' => 'レコード盤をイメージしたヴィンテージ感のあるデザイン。音楽ファンにぴったりの一枚。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 6,
                'shop_id' => 1,
                'secondary_category_id' => 1,
                'image1' => 9,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Acoustic Soul T-shirt',
                'information' => 'アコースティックギターとソウルフルな音楽をイメージしたシンプルなデザイン。ややゆったりめのフィット。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 7,
                'shop_id' => 1,
                'secondary_category_id' => 1,
                'image1' => 10,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Festival Lights T-shirt',
                'information' => '夜空に輝くフェスティバルのライトをデザインしたグラフィックTシャツ。イベントにぴったりのアイテム。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 8,
                'shop_id' => 2,
                'secondary_category_id' => 1,
                'image1' => 11,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Punk Attitude T-shirt',
                'information' => 'パンクロックのスピリットを表現した大胆なグラフィック。クラシックなブラックTシャツで、どんなスタイルにもマッチ。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 9,
                'shop_id' => 2,
                'secondary_category_id' => 1,
                'image1' => 12,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'EDM Wave T-shirt',
                'information' => 'EDMの高揚感を表現した波打つようなデザイン。軽量で汗をかいても快適に着られる。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 10,
                'shop_id' => 2,
                'secondary_category_id' => 1,
                'image1' => 13,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Classic Rock Revival T-shirt',
                'information' => 'クラシックロックの象徴的なギターモチーフをあしらったTシャツ。音楽好きの心を掴むデザイン。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 11,
                'shop_id' => 2,
                'secondary_category_id' => 1,
                'image1' => 14,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Chill Vibes T-shirt',
                'information' => 'リラックスした音楽の雰囲気を表現した、柔らかなパステルカラーのTシャツ。オーバーサイズでゆったり着こなせます。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 12,
                'shop_id' => 2,
                'secondary_category_id' => 1,
                'image1' => 15,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Hip-Hop Hustle T-shirt',
                'information' => 'ストリート感あふれるヒップホップのエッセンスを取り入れたグラフィック。耐久性のある素材で長持ちします。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 13,
                'shop_id' => 2,
                'secondary_category_id' => 1,
                'image1' => 16,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Synthwave Sunset T-shirt',
                'information' => '80年代のシンセウェーブを思わせる夕焼けのデザインが特徴。ノスタルジックな雰囲気が漂う一枚。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 14,
                'shop_id' => 2,
                'secondary_category_id' => 1,
                'image1' => 17,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Reggae Roots T-shirt',
                'information' => 'レゲエのルーツを象徴するカラフルなラスタデザイン。肌に優しいコットン素材で、自然な着心地を実現。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 15,
                'shop_id' => 3,
                'secondary_category_id' => 1,
                'image1' => 18,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Indie Spirit T-shirt',
                'information' => 'インディーミュージックの自由な精神を表現したミニマルデザイン。ベーシックなシルエットで、普段使いに最適。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 16,
                'shop_id' => 3,
                'secondary_category_id' => 1,
                'image1' => 19,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Metal Mayhem T-shirt',
                'information' => 'ヘビーメタルの激しいサウンドを反映したダークで迫力のあるデザイン。タフな素材で、過酷なライブシーンにも対応。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 17,
                'shop_id' => 3,
                'secondary_category_id' => 1,
                'image1' => 20,
                'image2' => 21,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Pop Star Dream T-shirt',
                'information' => 'キラキラしたポップスターの夢を象徴する星型デザイン。明るいカラーが特徴で、ポップミュージックファンに最適。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 18,
                'shop_id' => 3,
                'secondary_category_id' => 1,
                'image1' => 22,
                'image2' => 23,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Electric Nights Hoodie',
                'information' => 'エレクトリックな夜をイメージしたネオンカラーのデザイン。裏起毛で暖かく、寒い夜のフェスにも最適。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 19,
                'shop_id' => 1,
                'secondary_category_id' => 2,
                'image1' => 24,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Rock Anthem Hoodie',
                'information' => '伝説的なロックアンセムの歌詞がバックにプリントされたパーカー。厚手の素材で長時間の屋外イベントでも快適。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 20,
                'shop_id' => 1,
                'secondary_category_id' => 2,
                'image1' => 25,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Jazz Lounge Hoodie',
                'information' => 'ジャズクラブのラウンジをイメージしたシックなデザイン。ポケットにはミニ楽譜が刺繍されています。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 21,
                'shop_id' => 1,
                'secondary_category_id' => 2,
                'image1' => 26,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Festival Fever Hoodie',
                'information' => 'フェスティバルの熱気を感じさせるカラフルなフード内側のデザインが特徴。軽量素材で動きやすさを追求。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 22,
                'shop_id' => 1,
                'secondary_category_id' => 2,
                'image1' => 27,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Urban Beats Hoodie',
                'information' => '都市のビートを感じるクールなグラフィックデザイン。防風仕様で、どんな天候でも対応可能。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 23,
                'shop_id' => 1,
                'secondary_category_id' => 2,
                'image1' => 28,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Vinyl Vibes Hoodie',
                'information' => 'ヴィンテージレコードをモチーフにしたデザインで、音楽愛好者にぴったり。ソフトなコットン素材が快適さを提供。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 24,
                'shop_id' => 1,
                'secondary_category_id' => 2,
                'image1' => 29,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Acoustic Comfort Hoodie',
                'information' => 'アコースティックな音楽を楽しむ際にぴったりの、ゆったりとしたフィット感のパーカー。フード内側はギターの弦デザイン。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 25,
                'shop_id' => 1,
                'secondary_category_id' => 2,
                'image1' => 30,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Bassline Pulse Hoodie',
                'information' => '強烈なベースラインを視覚化した心電図風デザインが特徴。裏地にサーマル素材を使用し、保温性抜群。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 26,
                'shop_id' => 1,
                'secondary_category_id' => 2,
                'image1' => 31,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Punk Rock Rebel Hoodie',
                'information' => 'パンクロックの反抗的なスピリットを表現したデザイン。着崩したルックがカジュアルなシーンにぴったり。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 27,
                'shop_id' => 1,
                'secondary_category_id' => 2,
                'image1' => 32,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'EDM Glow Hoodie',
                'information' => '夜のEDMフェスにぴったりな、光を反射する素材を使用したパーカー。暗闇でも目立つこと間違いなし。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 28,
                'shop_id' => 1,
                'secondary_category_id' => 2,
                'image1' => 33,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Classic Groove Hoodie',
                'information' => 'クラシックな音楽スタイルを取り入れたミニマルデザイン。リブ編みの袖口と裾で、フィット感が良い。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 29,
                'shop_id' => 2,
                'secondary_category_id' => 2,
                'image1' => 34,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Chill Session Hoodie',
                'information' => 'リラックスした音楽セッションに最適な、柔らかな素材のパーカー。オーバーサイズでゆったりとした着心地。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 30,
                'shop_id' => 2,
                'secondary_category_id' => 2,
                'image1' => 35,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Hip-Hop Hustler Hoodie',
                'information' => 'ストリートスタイルを強調したヒップホップ風のグラフィック。カンガルーポケット付きで、利便性も抜群。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 31,
                'shop_id' => 2,
                'secondary_category_id' => 2,
                'image1' => 36,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Synthwave Dreams Hoodie',
                'information' => '80年代のシンセウェーブスタイルを反映したグラデーションカラー。フード部分はナイトシティのシルエットデザイン。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 32,
                'shop_id' => 2,
                'secondary_category_id' => 2,
                'image1' => 37,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Reggae Riddim Hoodie',
                'information' => 'レゲエのリズムとカラーを組み合わせたラスタ風デザイン。自然なフィット感で、リラックスしたスタイルにぴったり。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 33,
                'shop_id' => 2,
                'secondary_category_id' => 2,
                'image1' => 38,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Indie Vibes Hoodie',
                'information' => 'インディーミュージックの自由な雰囲気を感じさせるシンプルなデザイン。ベーシックなカラー展開で、どんなコーディネートにも合わせやすい。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 34,
                'shop_id' => 2,
                'secondary_category_id' => 2,
                'image1' => 39,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Metal Madness Hoodie',
                'information' => 'ヘビーメタルの激しいエネルギーを表現したダークなデザイン。耐久性に優れ、長時間の着用にも適しています。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 35,
                'shop_id' => 2,
                'secondary_category_id' => 2,
                'image1' => 40,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Pop Icons Hoodie',
                'information' => 'ポップミュージックの象徴的なアイコンが散りばめられたデザイン。カジュアルながらもスタイリッシュなアイテム。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 36,
                'shop_id' => 2,
                'secondary_category_id' => 2,
                'image1' => 41,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Blues Traveler Hoodie',
                'information' => 'ブルースの旅路をイメージしたデニム風のデザインが特徴。クラシックなスタイルで、どこか懐かしい雰囲気を醸し出します。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 37,
                'shop_id' => 2,
                'secondary_category_id' => 2,
                'image1' => 42,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'World Rhythms Hoodie',
                'information' => '世界中のリズムを感じさせるエスニックなデザイン。グローバルな音楽フェスにぴったりの一枚。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 38,
                'shop_id' => 2,
                'secondary_category_id' => 2,
                'image1' => 43,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Folk Harmony Hoodie',
                'information' => 'フォークミュージックの優しいハーモニーを表現したシンプルでナチュラルなデザイン。柔らかな素材でリラックスした着心地。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 39,
                'shop_id' => 3,
                'secondary_category_id' => 2,
                'image1' => 44,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Electro Fusion Hoodie',
                'information' => 'エレクトロミュージックと他ジャンルの融合を象徴する未来的なデザイン。モノトーンカラーで洗練されたスタイル。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 40,
                'shop_id' => 3,
                'secondary_category_id' => 2,
                'image1' => 45,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Rave Revival Hoodie',
                'information' => '90年代のレイブカルチャーをリバイバルしたネオンカラーと大胆なグラフィックデザイン。フェスで目立つこと間違いなし。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 41,
                'shop_id' => 3,
                'secondary_category_id' => 2,
                'image1' => 46,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Grunge Echo Hoodie',
                'information' => '90年代のグランジを象徴するディストレスト加工とシンプルなロゴデザイン。無骨でカジュアルなスタイルに合う。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 42,
                'shop_id' => 3,
                'secondary_category_id' => 2,
                'image1' => 47,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Ska Skankin’ Hoodie',
                'information' => 'スカミュージックの陽気なリズムを感じさせるチェッカーパターンデザイン。軽量で動きやすい。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 43,
                'shop_id' => 3,
                'secondary_category_id' => 2,
                'image1' => 48,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Ambient Chill Hoodie',
                'information' => 'アンビエントミュージックの落ち着いた雰囲気を反映したミニマルデザイン。リラックスしたい時に最適。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 44,
                'shop_id' => 3,
                'secondary_category_id' => 2,
                'image1' => 49,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Progressive Pulse Hoodie',
                'information' => 'プログレッシブな音楽のリズムを視覚化したパルスラインデザイン。未来的なスタイルで、都会的なルックに合う。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 45,
                'shop_id' => 3,
                'secondary_category_id' => 2,
                'image1' => 50,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Latin Groove Hoodie',
                'information' => 'ラテンミュージックの情熱を表現した鮮やかなカラーリングとリズミカルなグラフィック。ダンスイベントにぴったり。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 46,
                'shop_id' => 3,
                'secondary_category_id' => 2,
                'image1' => 51,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Celtic Harmony Hoodie',
                'information' => 'ケルト音楽の伝統を感じさせるノットワークデザイン。暖かく、自然な雰囲気が好きな人におすすめ。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 47,
                'shop_id' => 3,
                'secondary_category_id' => 2,
                'image1' => 52,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Trance Vision Hoodie',
                'information' => 'トランスミュージックのサイケデリックなビジョンを表現したデザイン。夜のイベントでも目を引く一枚。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 48,
                'shop_id' => 3,
                'secondary_category_id' => 2,
                'image1' => 53,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Melody Wave Sweatshirt',
                'information' => '音の波形をグラフィカルに表現したクールなデザイン。厚手のコットン素材で、季節の変わり目にも活躍します。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 49,
                'shop_id' => 1,
                'secondary_category_id' => 3,
                'image1' => 54,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Harmony Haven Sweatshirt',
                'information' => '音符が舞い上がるようなデザインで、音楽愛好家にぴったりの一枚。柔らかい裏起毛で、肌触りも抜群。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 50,
                'shop_id' => 1,
                'secondary_category_id' => 3,
                'image1' => 55,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Vinyl Revival Sweatshirt',
                'information' => 'ヴィンテージレコードをモチーフにしたクラシカルなデザイン。オーバーサイズでゆったりとしたフィット感が魅力。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 51,
                'shop_id' => 1,
                'secondary_category_id' => 3,
                'image1' => 56,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Bassline Beat Sweatshirt',
                'information' => '重低音のビートを象徴する波打つラインが胸元にプリントされたデザイン。音楽イベントに最適なカジュアルアイテム。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 52,
                'shop_id' => 2,
                'secondary_category_id' => 3,
                'image1' => 57,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Retro Rhythm Sweatshirt',
                'information' => '70年代のディスコを彷彿とさせるレトロなカラーリングが特徴のデザイン。どこか懐かしさを感じるアイテムです。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 53,
                'shop_id' => 2,
                'secondary_category_id' => 3,
                'image1' => 58,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Indie Spirit Sweatshirt',
                'information' => 'インディーミュージックの自由な精神を表現したミニマルなロゴデザイン。シンプルでどんなスタイルにも合わせやすい。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 54,
                'shop_id' => 3,
                'secondary_category_id' => 3,
                'image1' => 59,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Chillwave Sweatshirt',
                'information' => 'リラックスしたチルウェーブの雰囲気を反映したパステルカラーのデザイン。ゆったりとしたシルエットでリラックスタイムにぴったり。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 55,
                'shop_id' => 3,
                'secondary_category_id' => 3,
                'image1' => 60,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Sonic Wave Bomber Jacket',
                'information' => '音楽の波形をグラフィカルにプリントしたスタイリッシュなボンバージャケット。軽量で防風性があり、フェスやライブに最適。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 56,
                'shop_id' => 1,
                'secondary_category_id' => 4,
                'image1' => 61,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Rock Legends Leather Jacket',
                'information' => '伝説的なロックスターをイメージしたビンテージ風レザージャケット。耐久性に優れ、使うほどに味が出る一枚。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 57,
                'shop_id' => 1,
                'secondary_category_id' => 4,
                'image1' => 62,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Festival Fire Jacket',
                'information' => 'フェスの熱気を反映した鮮やかなカラーリングのジャケット。耐久性に優れ、アウトドアイベントやフェスにぴったりのデザイン。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 58,
                'shop_id' => 1,
                'secondary_category_id' => 4,
                'image1' => 63,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Festival Energy Jacket',
                'information' => 'フェスティバルのエネルギーを感じさせるカラフルなデザインが特徴のナイロンジャケット。防水性も兼ね備えており、どんな天候でも活躍。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 59,
                'shop_id' => 1,
                'secondary_category_id' => 4,
                'image1' => 64,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Rhythm and Blues Denim Jacket',
                'information' => 'ブルースとリズムを表現したヴィンテージデニムジャケット。クラシックなシルエットで、カジュアルなコーディネートにぴったり。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 60,
                'shop_id' => 1,
                'secondary_category_id' => 4,
                'image1' => 65,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Hip-Hop Streetwear Jacket',
                'information' => 'ストリート感溢れるヒップホップスタイルのジャケット。ゆったりとしたオーバーサイズで、アクティブなシーンに対応。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 61,
                'shop_id' => 2,
                'secondary_category_id' => 4,
                'image1' => 66,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'EDM Glow Reflective Jacket',
                'information' => '夜のEDMフェスにぴったりの光を反射するリフレクティブジャケット。暗闇でも視認性が高く、注目を集めること間違いなし。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 62,
                'shop_id' => 2,
                'secondary_category_id' => 4,
                'image1' => 67,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Indie Vibe Varsity Jacket',
                'information' => 'インディーミュージックの自由な雰囲気を表現したカジュアルなバーシティジャケット。カラーブロックデザインが特徴。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 63,
                'shop_id' => 2,
                'secondary_category_id' => 4,
                'image1' => 68,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Reggae Roots Track Jacket',
                'information' => 'レゲエのルーツを象徴するラスタカラーのトラックジャケット。軽量で通気性が良く、快適な着心地を提供。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 64,
                'shop_id' => 2,
                'secondary_category_id' => 4,
                'image1' => 69,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Metal Mayhem Utility Jacket',
                'information' => 'ヘビーメタルの迫力を感じさせるダークでクールなユーティリティジャケット。多機能ポケット付きで、実用性も兼ね備えています。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 65,
                'shop_id' => 2,
                'secondary_category_id' => 4,
                'image1' => 70,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Synthwave Neon Jacket',
                'information' => '80年代のシンセウェーブを思わせるネオンカラーが印象的なジャケット。未来的なデザインで、都会のナイトライフにぴったり。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 66,
                'shop_id' => 3,
                'secondary_category_id' => 4,
                'image1' => 71,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Acoustic Harmony Padded Jacket',
                'information' => 'アコースティックな音楽をテーマにした柔らかいカラーのパデッドジャケット。軽量で保温性が高く、寒い日でも暖かさをキープ。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 67,
                'shop_id' => 3,
                'secondary_category_id' => 4,
                'image1' => 72,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Punk Rock Rebel Moto Jacket',
                'information' => 'パンクロックの反抗的な精神を表現したライダースジャケット。タフなレザー素材で、スタイリッシュなロックスタイルを演出。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 68,
                'shop_id' => 3,
                'secondary_category_id' => 4,
                'image1' => 73,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Chillwave Comfort Fleece Jacket',
                'information' => 'リラックスしたチルウェーブの雰囲気を取り入れたフリースジャケット。柔らかくて暖かい、リラックスタイムに最適な一枚。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 69,
                'shop_id' => 3,
                'secondary_category_id' => 4,
                'image1' => 74,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Groove Snapback Cap',
                'information' => 'シンプルながらも洗練されたスナップバックキャップ。音楽のリズムを感じさせる波形ロゴがフロントに刺繍されています。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 70,
                'shop_id' => 1,
                'secondary_category_id' => 5,
                'image1' => 75,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Bass Drop Cap',
                'information' => '重低音を象徴する太いラインがデザインされたキャップ。ダークカラーで、クールなストリートスタイルにぴったりです。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 71,
                'shop_id' => 1,
                'secondary_category_id' => 5,
                'image1' => 76,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Retro Vinyl Cap',
                'information' => 'ヴィンテージレコードをモチーフにしたクラシカルなデザイン。柔らかいコットン素材で、普段使いにも最適。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 72,
                'shop_id' => 1,
                'secondary_category_id' => 5,
                'image1' => 77,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Festival Vibes Trucker Cap',
                'information' => '夏の音楽フェスにぴったりのメッシュバックのトラッカーキャップ。カラフルなデザインがイベント会場で目を引きます。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 73,
                'shop_id' => 2,
                'secondary_category_id' => 5,
                'image1' => 78,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Rock Rebel Cap',
                'information' => 'ロックなスピリットを表現したスカルモチーフのキャップ。デニム素材で、ヴィンテージ感が漂う一品です。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 74,
                'shop_id' => 2,
                'secondary_category_id' => 5,
                'image1' => 79,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Synthwave Sunset Cap',
                'information' => '80年代のシンセウェーブスタイルをイメージしたネオンカラーのキャップ。夜のイベントで映える光沢感のある素材が特徴です。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 75,
                'shop_id' => 2,
                'secondary_category_id' => 5,
                'image1' => 80,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Rhythm Rider Cap',
                'information' => 'リズムに乗るような音符デザインが特徴のキャップ。通気性の良いメッシュ素材で、ライブやフェスの暑い日にも快適に過ごせます。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 76,
                'shop_id' => 3,
                'secondary_category_id' => 5,
                'image1' => 81,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Hip-Hop Hustle Cap',
                'information' => 'ヒップホップカルチャーを象徴する大胆なロゴが入ったキャップ。ストリートスタイルに合うフラットブリムが特徴。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 77,
                'shop_id' => 3,
                'secondary_category_id' => 5,
                'image1' => 82,
                'image2' => 83,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Electric Wave Scarf Towel',
                'information' => '電子音楽のビートを表現した波形デザイン。吸水性に優れた素材で、フェスの汗もしっかりキャッチします。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 78,
                'shop_id' => 1,
                'secondary_category_id' => 6,
                'image1' => 84,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Rock Anthem Scarf Towel',
                'information' => 'ロックの名曲の歌詞がプリントされたデザイン。厚手のコットン素材で、ライブ会場でも目立つこと間違いなし。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 79,
                'shop_id' => 1,
                'secondary_category_id' => 6,
                'image1' => 85,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Jazz Harmony Scarf Towel',
                'information' => 'ジャズのリズムとハーモニーを表現したおしゃれなモノクロデザイン。通気性と速乾性が高く、いつでも快適。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 80,
                'shop_id' => 1,
                'secondary_category_id' => 6,
                'image1' => 86,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Bassline Groove Scarf Towel',
                'information' => '強烈なベースラインを視覚化したダイナミックなデザイン。吸水性の高い素材で、熱いライブでも大活躍。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 81,
                'shop_id' => 1,
                'secondary_category_id' => 6,
                'image1' => 87,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Festival Fire Scarf Towel',
                'information' => 'フェスの熱気を感じさせる炎をモチーフにした鮮やかなデザイン。柔らかな肌触りと高い耐久性が特徴。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 82,
                'shop_id' => 2,
                'secondary_category_id' => 6,
                'image1' => 88,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'EDM Pulse Scarf Towel',
                'information' => 'EDMのビートに合わせたパルスラインがデザインされたカラフルなタオル。長時間のイベントでも安心の吸収力。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 83,
                'shop_id' => 2,
                'secondary_category_id' => 6,
                'image1' => 89,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Punk Rock Rebel Scarf Towel',
                'information' => 'パンクロックの反抗的なスピリットを表現した大胆なグラフィックデザイン。激しいライブで汗を拭きながらもスタイルをキープ。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 84,
                'shop_id' => 2,
                'secondary_category_id' => 6,
                'image1' => 90,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Synthwave Neon Scarf Towel',
                'information' => '80年代のシンセウェーブをイメージしたネオンカラーのグラデーションデザイン。ソフトで肌に優しい素材を使用。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 85,
                'shop_id' => 3,
                'secondary_category_id' => 6,
                'image1' => 91,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Acoustic Vibes Scarf Towel',
                'information' => 'アコースティックなサウンドを思わせる温かみのあるデザイン。心地よいコットン素材で、普段使いにも最適。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 86,
                'shop_id' => 3,
                'secondary_category_id' => 6,
                'image1' => 92,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Reggae Roots Scarf Towel',
                'information' => 'レゲエのルーツを象徴するラスタカラーのカラフルなデザイン。速乾性の高い素材で、夏フェスにもぴったり。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 87,
                'shop_id' => 3,
                'secondary_category_id' => 6,
                'image1' => 93,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Beat Drop Face Towel',
                'information' => 'EDMのビートドロップをイメージした大胆なグラフィックデザイン。吸水性に優れたコットン素材で、汗をすぐに拭き取れます。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 88,
                'shop_id' => 1,
                'secondary_category_id' => 7,
                'image1' => 94,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Harmony Breeze Face Towel',
                'information' => '優雅な音符が風に舞うデザイン。柔らかくて肌に優しいタオルで、ライブや日常使いにもぴったり。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 89,
                'shop_id' => 1,
                'secondary_category_id' => 7,
                'image1' => 95,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Rock Vibes Face Towel',
                'information' => 'エッジの効いたロックなデザインが特徴のタオル。吸湿性が高く、長時間のイベントでも使いやすいアイテムです。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 90,
                'shop_id' => 2,
                'secondary_category_id' => 7,
                'image1' => 96,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Synthwave Glow Face Towel',
                'information' => 'シンセウェーブの光を反映したネオンカラーのフェイスタオル。速乾性があり、フェスやアウトドアで活躍します。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 91,
                'shop_id' => 2,
                'secondary_category_id' => 7,
                'image1' => 97,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Acoustic Rhythm Face Towel',
                'information' => 'アコースティックギターの弦をモチーフにしたナチュラルデザイン。ふんわりとした肌触りで、フェスの暑さを和らげます。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 92,
                'shop_id' => 3,
                'secondary_category_id' => 7,
                'image1' => 98,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Festival Spirit Face Towel',
                'information' => 'フェスティバルのエネルギーをカラフルなグラフィックで表現。軽量で持ち運びやすく、汗をしっかり吸収してくれます。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 93,
                'shop_id' => 3,
                'secondary_category_id' => 7,
                'image1' => 99,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Neon Beat Mini Towel',
                'information' => 'エレクトロミュージックのネオンビートを表現したカラフルなデザイン。コンパクトながらも高い吸水性を持ち、フェスやライブに最適です。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 94,
                'shop_id' => 1,
                'secondary_category_id' => 8,
                'image1' => 100,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Acoustic Echo Mini Towel',
                'information' => 'アコースティックな音の余韻をイメージしたシンプルで落ち着いたデザイン。柔らかい肌触りで、デイリーユースにも使いやすい一枚。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 95,
                'shop_id' => 1,
                'secondary_category_id' => 8,
                'image1' => 101,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Rave Vibes Mini Towel',
                'information' => 'レイブの熱気を感じさせる、鮮やかな色使いが特徴のタオル。軽量でポケットにも収まりやすく、すぐに汗を拭き取れます。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 96,
                'shop_id' => 2,
                'secondary_category_id' => 8,
                'image1' => 102,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Chill Beat Mini Towel',
                'information' => 'チルアウトした音楽をイメージしたリラックスデザイン。通気性が良く、暑い日でも肌に優しく快適に使えます。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 97,
                'shop_id' => 3,
                'secondary_category_id' => 8,
                'image1' => 103,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Beat Vibes Tote Bag',
                'information' => '音楽のビートが視覚化された大胆なデザインが特徴のトートバッグ。大容量でフェスや日常使いにも便利なアイテムです。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 98,
                'shop_id' => 1,
                'secondary_category_id' => 9,
                'image1' => 104,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Acoustic Harmony Tote Bag',
                'information' => 'アコースティックギターの弦をモチーフにしたナチュラルなデザイン。コットン素材で環境に優しく、リラックスした雰囲気を演出。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 99,
                'shop_id' => 1,
                'secondary_category_id' => 9,
                'image1' => 105,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Electric Pulse Tote Bag',
                'information' => 'エレクトロニックなパルスラインがデザインされたクールなトートバッグ。耐久性が高く、ライブグッズや買い物にも使いやすいサイズ感。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 100,
                'shop_id' => 1,
                'secondary_category_id' => 9,
                'image1' => 106,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Indie Spirit Tote Bag',
                'information' => 'インディーミュージックの自由な精神を表現したシンプルなデザイン。どんなスタイルにも合わせやすく、普段使いにも最適なアイテム。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 101,
                'shop_id' => 2,
                'secondary_category_id' => 9,
                'image1' => 107,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Festival Sunset Tote Bag',
                'information' => 'フェスティバルの夕焼けをイメージしたグラデーションカラーのトートバッグ。軽量で持ち運びやすく、イベントやアウトドアにぴったり。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 102,
                'shop_id' => 2,
                'secondary_category_id' => 9,
                'image1' => 108,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Vinyl Revival Tote Bag',
                'information' => 'ヴィンテージレコードをモチーフにしたレトロなデザインが特徴。レコード好きの音楽ファンにぴったりのトートバッグ。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 103,
                'shop_id' => 2,
                'secondary_category_id' => 9,
                'image1' => 109,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Synthwave Dreams Tote Bag',
                'information' => 'Synthwave Dreams Tote Bag',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 104,
                'shop_id' => 3,
                'secondary_category_id' => 9,
                'image1' => 110,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Rock Legends Tote Bag',
                'information' => '伝説的なロックスターたちを象徴するシルエットがプリントされたトートバッグ。丈夫な素材で、ライブグッズやアクセサリーを持ち運ぶのに最適。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 105,
                'shop_id' => 3,
                'secondary_category_id' => 9,
                'image1' => 111,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Rhythm Flow Shoulder Bag',
                'information' => '音楽のリズムが流れるようなラインデザインが特徴のコンパクトショルダーバッグ。フェスやライブに必要な小物をまとめて持ち運ぶのに便利なサイズ感。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 106,
                'shop_id' => 1,
                'secondary_category_id' => 10,
                'image1' => 112,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Bassline Beat Shoulder Bag',
                'information' => 'ベースラインの力強さを象徴するブラックとグレーのコントラストデザイン。耐水性があり、アウトドアイベントにもぴったりです。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 107,
                'shop_id' => 1,
                'secondary_category_id' => 10,
                'image1' => 113,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Electric Pulse Shoulder Bag',
                'information' => 'エレクトリックなパルスをイメージした鮮やかな色使いが魅力のショルダーバッグ。軽量で、長時間のイベントでも肩が疲れにくい設計。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 108,
                'shop_id' => 2,
                'secondary_category_id' => 10,
                'image1' => 114,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Indie Groove Shoulder Bag',
                'information' => 'インディーミュージックの自由な精神を表現したミニマルデザインのショルダーバッグ。ちょっとした外出やフェスにもぴったりな、スタイリッシュな一品。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 109,
                'shop_id' => 3,
                'secondary_category_id' => 10,
                'image1' => 115,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Festival Vibes Rubber Band',
                'information' => 'フェスティバルの活気を反映したカラフルなグラデーションデザイン。シンプルながらも目を引くデザインで、音楽イベントの思い出としても最適なアイテムです。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 110,
                'shop_id' => 1,
                'secondary_category_id' => 11,
                'image1' => 116,
                'image2' => 117,
                'image3' => 118,
                'image4' => null,
            ],
            [
                'name' => 'Electric Vibe Keychain',
                'information' => '電子音楽のビートを表現したネオンカラーのキーホルダー。軽量で、バッグや鍵につけるだけでフェス気分を盛り上げます。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 111,
                'shop_id' => 1,
                'secondary_category_id' => 12,
                'image1' => 119,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Rock Legend Guitar Keychain',
                'information' => 'ミニギターをモチーフにしたメタル製キーホルダー。ロックファンにはたまらない、重厚感のあるデザインが特徴です。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 112,
                'shop_id' => 1,
                'secondary_category_id' => 12,
                'image1' => 120,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Vinyl Groove Keychain',
                'information' => 'ヴィンテージレコード盤をミニサイズで再現したキーホルダー。レコード好きな音楽ファンにぴったりの一品です。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 113,
                'shop_id' => 1,
                'secondary_category_id' => 12,
                'image1' => 121,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Bassline Pulse Keychain',
                'information' => 'ベースラインを象徴する音符とパルスデザインが組み合わされたユニークなキーホルダー。ライブのエネルギーを持ち歩くような感覚に。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 114,
                'shop_id' => 1,
                'secondary_category_id' => 12,
                'image1' => 122,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Synthwave Neon Keychain',
                'information' => '80年代のシンセウェーブをイメージしたネオンカラーのアクリルキーホルダー。光沢のある仕上がりで、目を引くデザイン。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 115,
                'shop_id' => 2,
                'secondary_category_id' => 12,
                'image1' => 123,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Acoustic Melody Keychain',
                'information' => 'アコースティックギターの形をした木製キーホルダー。温かみのあるデザインで、ナチュラルな音楽の雰囲気を持ち運べます。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 116,
                'shop_id' => 2,
                'secondary_category_id' => 12,
                'image1' => 124,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Festival Sunset Keychain',
                'information' => 'フェスティバルの夕焼けを表現したカラフルなデザインが特徴。ポップなカラーリングでフェスの思い出を残すアイテムです。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 117,
                'shop_id' => 2,
                'secondary_category_id' => 12,
                'image1' => 125,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Punk Rebel Keychain',
                'information' => 'パンクロックの反抗的なスピリットを象徴するスカルとチェーンデザインのキーホルダー。強さとスタイルをアピールする一品。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 118,
                'shop_id' => 2,
                'secondary_category_id' => 12,
                'image1' => 126,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Indie Spirit Keychain',
                'information' => 'インディーミュージックの自由な精神を表現したシンプルなロゴデザインのキーホルダー。どんなスタイルにも合わせやすいミニマルなデザイン。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 119,
                'shop_id' => 3,
                'secondary_category_id' => 12,
                'image1' => 127,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'EDM Glow Keychain',
                'information' => 'EDMフェスの夜を照らすライトアップ効果のあるキーホルダー。暗闇で光るので、ナイトイベントで目立ちます。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 120,
                'shop_id' => 3,
                'secondary_category_id' => 12,
                'image1' => 128,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'World Music Journey Keychain',
                'information' => '世界中の音楽を象徴する民族楽器のミニチュアがついたエスニックデザインのキーホルダー。グローバルな音楽ファンにぴったりです。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 121,
                'shop_id' => 3,
                'secondary_category_id' => 12,
                'image1' => 129,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Electric Pulse Badge',
                'information' => '電子音楽のビートを視覚化したパルスラインがデザインされたメタル製バッジ。光沢のある仕上げで、どんなジャケットやバッグにも映えるアイテム。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 122,
                'shop_id' => 1,
                'secondary_category_id' => 13,
                'image1' => 130,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Rock Rebel Skull Badge',
                'information' => 'パンクロックを象徴するスカルとクロスボーンがデザインされたバッジ。反抗的なスピリットを持ったロックファンにぴったり。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 123,
                'shop_id' => 1,
                'secondary_category_id' => 13,
                'image1' => 131,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Vinyl Revival Badge',
                'information' => 'ヴィンテージレコード盤をモチーフにしたクラシックなデザインのバッジ。音楽愛好者が集まるイベントに最適な一品。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 124,
                'shop_id' => 1,
                'secondary_category_id' => 13,
                'image1' => 132,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Festival Vibes Badge',
                'information' => 'フェスティバルの熱気をカラフルに表現したバッジ。ポップなデザインで、フェスの思い出をいつでも楽しめるアイテムです。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 125,
                'shop_id' => 2,
                'secondary_category_id' => 13,
                'image1' => 133,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Indie Spirit Badge',
                'information' => 'インディーミュージックの自由な精神を象徴するシンプルでスタイリッシュなデザイン。ミニマルなスタイルが魅力です。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 126,
                'shop_id' => 2,
                'secondary_category_id' => 13,
                'image1' => 134,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Synthwave Dreams Badge',
                'information' => '80年代のシンセウェーブをイメージしたネオンカラーと幾何学模様のバッジ。レトロ感のあるデザインで、ファッションのアクセントに。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 127,
                'shop_id' => 3,
                'secondary_category_id' => 13,
                'image1' => 135,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Acoustic Soul Badge',
                'information' => 'アコースティックギターをモチーフにした木目調のバッジ。ナチュラルな音楽の雰囲気を持ち歩ける、温かみのあるデザインが特徴。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 128,
                'shop_id' => 3,
                'secondary_category_id' => 13,
                'image1' => 136,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Neon Beat Sticker',
                'information' => 'エレクトロミュージックのビートを視覚化したネオンカラーのステッカー。ノートパソコンやスマホケースに貼って、フェスのエネルギーをいつでも感じられるデザイン。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 129,
                'shop_id' => 1,
                'secondary_category_id' => 14,
                'image1' => 137,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Vinyl Vibes Sticker',
                'information' => 'ヴィンテージレコードをモチーフにしたレトロなデザインのステッカー。レコードプレーヤーや楽器ケースに貼って、音楽への情熱をアピール。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 130,
                'shop_id' => 1,
                'secondary_category_id' => 14,
                'image1' => 138,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Festival Fire Sticker',
                'information' => 'フェスティバルの熱気を表現したカラフルでダイナミックなデザインのステッカー。アウトドアギアや水筒に貼ってフェスの雰囲気を楽しめます。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 131,
                'shop_id' => 2,
                'secondary_category_id' => 14,
                'image1' => 139,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Acoustic Harmony Sticker',
                'information' => 'アコースティックなメロディーをイメージしたシンプルで温かみのあるデザインのステッカー。ギターケースや日常のアイテムに貼って、ナチュラルな音楽スタイルを表現。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 132,
                'shop_id' => 3,
                'secondary_category_id' => 14,
                'image1' => 140,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Festival Moments Calendar',
                'information' => '世界中の音楽フェスティバルの名場面を毎月楽しめるカレンダー。フェスの熱気やライブの臨場感を写真で感じながら、1年を通じて音楽の雰囲気を満喫できます。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 133,
                'shop_id' => 1,
                'secondary_category_id' => 15,
                'image1' => 141,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Rock Legends Calendar',
                'information' => '伝説的なロックスターたちのライブ写真やアルバムカバーをフィーチャーしたカレンダー。毎月異なるロックアーティストの魅力を堪能でき、音楽好きにはたまらない一品です。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 134,
                'shop_id' => 2,
                'secondary_category_id' => 15,
                'image1' => 142,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Acoustic Harmony Calendar',
                'information' => 'アコースティックなライブや音楽セッションの風景を集めたカレンダー。自然の中で演奏される音楽シーンや、温かみのあるデザインでリラックスできる1年を演出します。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 135,
                'shop_id' => 3,
                'secondary_category_id' => 15,
                'image1' => 143,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Neon Beats iPhone Case',
                'information' => 'EDMのネオンビートを象徴する鮮やかなカラーリングが特徴のケース。耐衝撃性に優れ、スタイリッシュなデザインで、フェスの雰囲気をいつでも持ち歩けます。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 136,
                'shop_id' => 1,
                'secondary_category_id' => 16,
                'image1' => 144,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Vinyl Groove iPhone Case',
                'information' => 'ヴィンテージレコードの質感を再現したレトロデザイン。スリムでありながら、スマホをしっかり保護し、音楽ファンにぴったりのスタイリッシュなケースです。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 137,
                'shop_id' => 2,
                'secondary_category_id' => 16,
                'image1' => 145,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
            [
                'name' => 'Acoustic Vibes iPhone Case',
                'information' => 'アコースティックギターの弦とウッドの質感を表現したナチュラルなデザイン。音楽を愛するユーザーのために、優れたグリップ感と耐久性を兼ね備えています。',
                'price' => $this->randomNumber(),
                'is_selling' => 1,
                'sort_order' => 138,
                'shop_id' => 3,
                'secondary_category_id' => 16,
                'image1' => 146,
                'image2' => null,
                'image3' => null,
                'image4' => null,
            ],
        ]);
    }

    private function randomNumber()
    {
        return rand(1000, 8000);
    }
}
